name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}
          project_id: ${{ secrets.GCP_PROJECT_ID_DEV }}
      
      -
        name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      -
        name: Use gcloud CLI
        run: gcloud info

      -
        name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
        
      -
        name: Build Image
        run: |
          docker build \
            -f Dockerfile \
            -t n8nd:${{ github.sha }} . \
            --network=host

      -
        name: Tag Image
        run: |
          docker tag \
            n8nd:${{ github.sha }} \
            us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_DEV }}/digi/n8nd:${{ github.sha }}
      
      -
        name: Push Image
        run: |
          docker push \
            us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_DEV }}/digi/n8nd:${{ github.sha }}

      -
        name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy n8nd \
            --concurrency 80 \
            --min-instances 0 \
            --max-instances 1 \
            --timeout 300s \
            --cpu 1 \
            --memory 512Mi \
            --image us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_DEV }}/digi/n8nd:${{ github.sha }} \
            --region us-east1 \
            --allow-unauthenticated \
            --service-account ${{ secrets.GCP_SA_EMAIL_DEV }}

      -
        name: remove image from artifact registry
        run: |
          gcloud container images delete \
            us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_DEV }}/digi/n8nd:${{ github.sha }} \
            --force-delete-tags \
            --quiet
